#!/usr/bin/env bash

if [ $# == 0 ]; then
  echo "Please specify the app name as a command line argument"
  exit 1
fi

app_name=$1
git clone https://github.com/PlayLikeNeverB4/rails-react-starter-kit.git $app_name
cd $app_name

yarn install

rm -rf .git
git init

if [ $# > 1 ]; then
  repo_url=$2
  echo "Setting remote url to $repo_url"
  git remote add origin $repo_url
else
  echo "No repo url provided"
fi

git add .
git commit -m "Set up project"
# https://github.com/PlayLikeNeverB4/devsimulator.git
